/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.grocery.main;

import com.grocery.db.DB;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Gayani
 */
public class Report extends javax.swing.JInternalFrame {

    double cash_total, card_total, both_total, profit;
    int sales;

    /**
     * Creates new form Dashboard
     */
    public Report() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI b1 = (BasicInternalFrameUI) this.getUI();
        b1.setNorthPane(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JPanel();
        btn_invoice = new javax.swing.JButton();
        btn_employee = new javax.swing.JButton();
        btn_stock = new javax.swing.JButton();
        btn_summary = new javax.swing.JButton();
        btn_employee1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1620, 860));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jDesktopPane1.setBackground(new java.awt.Color(0, 153, 51));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(1100, 450));

        btn_invoice.setBackground(new java.awt.Color(0, 153, 51));
        btn_invoice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_invoice.setForeground(new java.awt.Color(255, 255, 255));
        btn_invoice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/grocery/images/4306906.png"))); // NOI18N
        btn_invoice.setText("Invoice");
        btn_invoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_invoiceActionPerformed(evt);
            }
        });

        btn_employee.setBackground(new java.awt.Color(0, 153, 51));
        btn_employee.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_employee.setForeground(new java.awt.Color(255, 255, 255));
        btn_employee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/grocery/images/3616930.png"))); // NOI18N
        btn_employee.setText("Employee");
        btn_employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_employeeActionPerformed(evt);
            }
        });

        btn_stock.setBackground(new java.awt.Color(0, 153, 51));
        btn_stock.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_stock.setForeground(new java.awt.Color(255, 255, 255));
        btn_stock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/grocery/images/stock-market-analysis-report-6456749-5348957.png"))); // NOI18N
        btn_stock.setText("Stock");
        btn_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stockActionPerformed(evt);
            }
        });

        btn_summary.setBackground(new java.awt.Color(0, 153, 51));
        btn_summary.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_summary.setForeground(new java.awt.Color(255, 255, 255));
        btn_summary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/grocery/images/3616930.png"))); // NOI18N
        btn_summary.setText("Summary");
        btn_summary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_summaryActionPerformed(evt);
            }
        });

        btn_employee1.setBackground(new java.awt.Color(0, 153, 51));
        btn_employee1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_employee1.setForeground(new java.awt.Color(255, 255, 255));
        btn_employee1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/grocery/images/9dff72a7f4e082be0150145258a82d16.png"))); // NOI18N
        btn_employee1.setText("GRN");
        btn_employee1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_employee1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(93, 93, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_summary, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_employee, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(btn_invoice, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btn_employee1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(btn_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(btn_employee, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_employee1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_invoice, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(btn_summary, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 983, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1000, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_invoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_invoiceActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        Invoice inv = new Invoice();
        jDesktopPane1.add(inv).setVisible(true);
    }//GEN-LAST:event_btn_invoiceActionPerformed

    private void btn_employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_employeeActionPerformed
        jDesktopPane1.removeAll();
        Employee emp = new Employee();
        jDesktopPane1.add(emp).setVisible(true);
    }//GEN-LAST:event_btn_employeeActionPerformed

    private void btn_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stockActionPerformed
        jDesktopPane1.removeAll();
        Stock s = new Stock();
        jDesktopPane1.add(s).setVisible(true);
    }//GEN-LAST:event_btn_stockActionPerformed

    private void btn_summaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_summaryActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        Summary sum = new Summary();
        jDesktopPane1.add(sum).setVisible(true);
    }//GEN-LAST:event_btn_summaryActionPerformed

    private void btn_employee1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_employee1ActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        GRNReports grnr = new GRNReports();
        jDesktopPane1.add(grnr).setVisible(true);
    }//GEN-LAST:event_btn_employee1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_employee;
    private javax.swing.JButton btn_employee1;
    private javax.swing.JButton btn_invoice;
    private javax.swing.JButton btn_stock;
    private javax.swing.JButton btn_summary;
    private javax.swing.JPanel jDesktopPane1;
    // End of variables declaration//GEN-END:variables



}
