/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.grocery.main.sub;

import com.grocery.db.DB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Gayani
 */
public class BrandManagement extends javax.swing.JFrame {

    /**
     * Creates new form Category
     */
    public BrandManagement() {
        initComponents();
        catagory();
        idSearch();
        empidgenerate();
    }
    
    Connection con1;
    PreparedStatement stm;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_brandid = new javax.swing.JTextField();
        txt_brandname = new javax.swing.JTextField();
        txt_description = new javax.swing.JScrollPane();
        txt_branddescription = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        btn_add1 = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        btn_delete1 = new javax.swing.JButton();
        combo_cat = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        combo_idsearch = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        btn_search = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel8.setText("Brand");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel9.setText("Green Grocers");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel10.setText("Brand Name ");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 45));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel11.setText("Description");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 116, 45));

        txt_brandid.setEditable(false);
        txt_brandid.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txt_brandid.setPreferredSize(new java.awt.Dimension(111, 23));
        txt_brandid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_brandidActionPerformed(evt);
            }
        });
        jPanel3.add(txt_brandid, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 249, 45));

        txt_brandname.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txt_brandname.setPreferredSize(new java.awt.Dimension(111, 23));
        jPanel3.add(txt_brandname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 249, 45));

        txt_branddescription.setColumns(20);
        txt_branddescription.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_branddescription.setRows(5);
        txt_description.setViewportView(txt_branddescription);

        jPanel3.add(txt_description, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 249, 47));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel12.setText("Category  ");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 125, -1, 45));

        btn_add1.setBackground(new java.awt.Color(204, 204, 204));
        btn_add1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btn_add1.setText("Add");
        btn_add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add1ActionPerformed(evt);
            }
        });
        jPanel3.add(btn_add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 100, 45));

        btn_update.setBackground(new java.awt.Color(204, 204, 204));
        btn_update.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel3.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 100, 45));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel17.setText("Brand ID");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 15, 116, 45));

        btn_delete1.setBackground(new java.awt.Color(204, 204, 204));
        btn_delete1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btn_delete1.setText("Delete");
        btn_delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete1ActionPerformed(evt);
            }
        });
        jPanel3.add(btn_delete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 90, 45));

        combo_cat.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jPanel3.add(combo_cat, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 250, 40));

        jButton4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 100, 50));

        combo_idsearch.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel16.setText("Brand ID");

        btn_search.setBackground(new java.awt.Color(204, 204, 204));
        btn_search.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combo_idsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(6, 6, 6)
                .addComponent(jLabel8)
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_idsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_search)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_brandidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_brandidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_brandidActionPerformed

    private void btn_add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add1ActionPerformed
        String id = txt_brandid.getText();
        String name = txt_brandname.getText();
        String description = txt_branddescription.getText();
        
       

        try {
            DB.push("insert into brand  values('" +id + "','" + name + "','"+combo_cat.getSelectedItem().toString().split("-")[0]
                    +"','" + description + "','1')");
            JOptionPane.showMessageDialog(this, "brand  saved successfully", "success", JOptionPane.INFORMATION_MESSAGE);
            empidgenerate();
            Clear();
            idSearch();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_add1ActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        String id = txt_brandid.getText();
        String name = txt_brandname.getText();
        String description = txt_branddescription.getText();
        
       

        try {
            DB.push("update brand set brand_name='"+name+"', brand_category='"+combo_cat.getSelectedItem().toString().split("-")[0]+"', brand_description='"+description+"' where brand_id ='"+id+"'"); 
                    
            JOptionPane.showMessageDialog(this, "brand  saved successfully", "success", JOptionPane.INFORMATION_MESSAGE);
            empidgenerate();
            Clear();
            idSearch();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, String.valueOf(e), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete1ActionPerformed
         try {
            DB.push("UPDATE `brand` SET brand_status= 0 WHERE brand_id= '" + combo_idsearch.getSelectedItem() + "'");
            JOptionPane.showMessageDialog(this, "`Brand deleted success", "success", JOptionPane.INFORMATION_MESSAGE);
            empidgenerate();
            Clear();
            idSearch();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, String.valueOf(e), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_delete1ActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        try {
            String brandid = combo_idsearch.getSelectedItem().toString();
            ResultSet rs = DB.search("select * from brand where brand_id = '" +brandid+ "'");
            if (rs.next()) {
                boolean status = rs.getBoolean("brand_status");
                if (status) {
                    txt_brandid.setText(rs.getString("brand_id"));
                    txt_brandname.setText(rs.getString("brand_name"));
                    txt_branddescription.setText(rs.getString("brand_description"));
                    String catid = rs.getString("brand_category").toString();
                    combo_cat.setSelectedItem(catid);
                    

                } else {
                    JOptionPane.showMessageDialog(this, "brand is not Active", "error", JOptionPane.ERROR_MESSAGE);

                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_searchActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        Clear();
    }//GEN-LAST:event_jButton4ActionPerformed
    
   
       
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BrandManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BrandManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BrandManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BrandManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BrandManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add1;
    private javax.swing.JButton btn_delete1;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> combo_cat;
    private javax.swing.JComboBox<String> combo_idsearch;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextArea txt_branddescription;
    private javax.swing.JTextField txt_brandid;
    private javax.swing.JTextField txt_brandname;
    private javax.swing.JScrollPane txt_description;
    // End of variables declaration//GEN-END:variables

    private void idSearch() {
        try {
            ResultSet rs = DB.search("select * from brand where brand_status = 1");
            Vector v = new Vector();

            while (rs.next()) {
                String data = rs.getString("brand_id");
                v.add(data);
            }

            combo_idsearch.setModel(new DefaultComboBoxModel(v));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    
    private void empidgenerate() {
         try {

            ResultSet rs = DB.search("select count(*) as empid from brand");
            if (rs.next()) {
                int Count = rs.getInt("empid");
                String id = "B" + (++Count);
                txt_brandid.setText(id);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

     private void catagory() {
        try {
            ResultSet rs = DB.search("select * from category");
            Vector v = new Vector();

            while (rs.next()) {
                String data = rs.getString("cat_id")+"-"+rs.getString("cat_name");
                v.add(data);
            }

            combo_cat.setModel(new DefaultComboBoxModel(v));
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void Clear() {
        
        txt_brandname.setText(null);
        txt_branddescription.setText(null);
        combo_cat.setSelectedIndex(0);
        
        
    }
}
