/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.grocery.main.sub;

import com.grocery.db.DB;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import com.grocery.main.Category;


/**
 *
 * @author Gayani
 */
public class CategoryManagement extends javax.swing.JFrame {

    /**
     * Creates new form Category
     */
    public CategoryManagement() {
        initComponents();
        idSearch();
        empidgenerate();
        setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_catid = new javax.swing.JTextField();
        txt_catname = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_catdescription = new javax.swing.JTextArea();
        combo_catstatus = new javax.swing.JComboBox<>();
        btn_add1 = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        btn_delete1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        combo_idsearch = new javax.swing.JComboBox<>();
        btn_search = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel8.setText(" Category");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel9.setText("Green Grocers");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 1, 14))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel10.setText("Category Name ");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 45));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel11.setText("Description");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 116, 45));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel15.setText("Status");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 116, 45));

        txt_catid.setEditable(false);
        txt_catid.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txt_catid.setPreferredSize(new java.awt.Dimension(111, 23));
        txt_catid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_catidActionPerformed(evt);
            }
        });
        jPanel3.add(txt_catid, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 249, 45));

        txt_catname.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txt_catname.setPreferredSize(new java.awt.Dimension(111, 23));
        jPanel3.add(txt_catname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 249, 45));

        txt_catdescription.setColumns(20);
        txt_catdescription.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txt_catdescription.setRows(5);
        jScrollPane2.setViewportView(txt_catdescription);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 249, 47));

        combo_catstatus.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        combo_catstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Inactive" }));
        jPanel3.add(combo_catstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 249, -1));

        btn_add1.setBackground(new java.awt.Color(204, 204, 204));
        btn_add1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btn_add1.setText("Add");
        btn_add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add1ActionPerformed(evt);
            }
        });
        jPanel3.add(btn_add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 100, 45));

        btn_update.setBackground(new java.awt.Color(204, 204, 204));
        btn_update.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel3.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 110, 45));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel17.setText("Category ID");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 15, 116, 45));

        btn_delete1.setBackground(new java.awt.Color(204, 204, 204));
        btn_delete1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btn_delete1.setText("Delete");
        btn_delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete1ActionPerformed(evt);
            }
        });
        jPanel3.add(btn_delete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 100, 45));

        jButton4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 100, 50));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel16.setText("Category ID");

        combo_idsearch.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N

        btn_search.setBackground(new java.awt.Color(204, 204, 204));
        btn_search.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo_idsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_idsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_search)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_catidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_catidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_catidActionPerformed


    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        try {
            String catid = combo_idsearch.getSelectedItem().toString();
            ResultSet rs = DB.search("select * from category where cat_id = '" + catid + "'");
            if (rs.next()) {
                boolean status = rs.getBoolean("cat_status");
                if (status) {
                    
                    txt_catid.setText(rs.getString("cat_id"));
                    txt_catname.setText(rs.getString("cat_name"));
                    txt_catdescription.setText(rs.getString("cat_description"));
                    combo_catstatus.setSelectedItem("cat_status");

                } else {
                    JOptionPane.showMessageDialog(this, "Category is not Active", "error", JOptionPane.ERROR_MESSAGE);

                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_btn_searchActionPerformed

    String st1;
    private void btn_add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add1ActionPerformed
        String id = txt_catid.getText();
        String name = txt_catname.getText();
        String description = txt_catdescription.getText();
        String status = combo_catstatus.getSelectedItem().toString();
        if (status.trim().equals("Active")) {
            int st = 1;
            st1 = "" + st;
        } else {
            int st = 0;
            st1 = "" + st;
        }

        try {
            DB.push("insert into category  values('" + id + "','" + name + "','" + description + "','" + st1 + "')");
            JOptionPane.showMessageDialog(this, "category  saved successfully", "success", JOptionPane.INFORMATION_MESSAGE);
            empidgenerate();
            idSearch();
            Clear();
            Category c = new Category();
            c.addDataToTable();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btn_add1ActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        String status = combo_catstatus.getSelectedItem().toString();
        if (status.trim().equals("Active")) {
            int st = 1;
            st1 = "" + st;
        } else {
            int st = 0;
            st1 = "" + st;
        }
        try {
            DB.push("update category set cat_name = '" + txt_catname.getText() + "', cat_description = '" + txt_catdescription.getText() + "', cat_status='" + st1 + "'  where cat_id = '" + txt_catid.getText() + "' ");
            JOptionPane.showMessageDialog(this, "Category updated success", "success", JOptionPane.INFORMATION_MESSAGE);
            empidgenerate();
            Clear();
        } catch (Exception e) {
           JOptionPane.showMessageDialog(this, String.valueOf(e), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete1ActionPerformed
        
        try {
            DB.push("update category set cat_status = '0' where cat_id = '" + combo_idsearch.getSelectedItem() + "'");
            JOptionPane.showMessageDialog(this, "Category deleted success", "success", JOptionPane.INFORMATION_MESSAGE);
            empidgenerate();
            Clear();
            idSearch();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, String.valueOf(e), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_delete1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        Clear();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void idSearch() {
        try {
            ResultSet rs = DB.search("select * from category where cat_status = 1");
            Vector v = new Vector();

            while (rs.next()) {
                String data = rs.getString("cat_id");
                v.add(data);
            }

            combo_idsearch.setModel(new DefaultComboBoxModel(v));
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CategoryManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CategoryManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CategoryManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CategoryManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CategoryManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add1;
    private javax.swing.JButton btn_delete1;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> combo_catstatus;
    private javax.swing.JComboBox<String> combo_idsearch;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txt_catdescription;
    private javax.swing.JTextField txt_catid;
    private javax.swing.JTextField txt_catname;
    // End of variables declaration//GEN-END:variables

    private void empidgenerate() {
        try {

            ResultSet rs = DB.search("select count(*) as empid from category");
            if (rs.next()) {
                int Count = rs.getInt("empid");
                String id = "CAT" + (++Count);
                txt_catid.setText(id);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void Clear() {
        txt_catname.setText(null);
        txt_catdescription.setText(null);
    }
}
