/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.grocery.main.sub;

import com.grocery.db.comman.SystemConfigData;
import com.grocery.main.Brand;
import com.grocery.main.Category;
import com.grocery.main.Dashboard;
import com.grocery.main.Employee;
import com.grocery.main.GRN;
import com.grocery.main.PO;
import com.grocery.main.POS;
import com.grocery.main.Report;
import com.grocery.main.Stock;
import com.grocery.main.Supplier;
import com.grocery.main.sub.inner.Inactiveted_Types;
import com.grocery.main.sub.inner.Userprofile;
import org.apache.log4j.Logger;
//mport grocery.Category;

/**
 *
 * @author Gayani
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form homeview
     */
    public Home() {
        initComponents();
        u_name.setText(SystemConfigData.getUsername());
        u_type.setText(SystemConfigData.getUsertype());
        Dashboard p = new Dashboard();
        jDesktopPane1.add(p).setVisible(true);
        showbutton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        u_type = new javax.swing.JLabel();
        u_name = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();
        btn_profile = new javax.swing.JButton();
        btn_stock = new javax.swing.JButton();
        btn_reports = new javax.swing.JButton();
        btn_employee = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btn_grn = new javax.swing.JButton();
        btn_pos = new javax.swing.JButton();
        btn_brand = new javax.swing.JButton();
        btn_pos1 = new javax.swing.JButton();
        btn_category = new javax.swing.JButton();
        btn_po = new javax.swing.JButton();
        btn_supplier = new javax.swing.JButton();
        btn_po1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 51));
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));

        u_type.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        u_type.setForeground(new java.awt.Color(255, 255, 255));
        u_type.setText("Name");

        u_name.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        u_name.setForeground(new java.awt.Color(255, 255, 255));
        u_name.setText("Name");

        btn_logout.setBackground(new java.awt.Color(51, 51, 0));
        btn_logout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(51, 51, 0));
        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/grocery/images/3596144.png"))); // NOI18N
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        btn_profile.setBackground(new java.awt.Color(51, 51, 0));
        btn_profile.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_profile.setForeground(new java.awt.Color(255, 255, 255));
        btn_profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/grocery/images/1200px-Add_user_icon_28blue29.svg.png"))); // NOI18N
        btn_profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_profileActionPerformed(evt);
            }
        });

        btn_stock.setBackground(new java.awt.Color(51, 51, 0));
        btn_stock.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_stock.setForeground(new java.awt.Color(255, 255, 255));
        btn_stock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/grocery/images/stock-market-analysis-report-6456749-5348957.png"))); // NOI18N
        btn_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stockActionPerformed(evt);
            }
        });

        btn_reports.setBackground(new java.awt.Color(51, 51, 0));
        btn_reports.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_reports.setForeground(new java.awt.Color(255, 255, 255));
        btn_reports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/grocery/images/1024px-Reports_Flat_Icon.svg.png"))); // NOI18N
        btn_reports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reportsActionPerformed(evt);
            }
        });

        btn_employee.setBackground(new java.awt.Color(51, 51, 0));
        btn_employee.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_employee.setForeground(new java.awt.Color(255, 255, 255));
        btn_employee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/grocery/images/3616930.png"))); // NOI18N
        btn_employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_employeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(u_type, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(u_name, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(625, 625, 625)
                .addComponent(btn_employee)
                .addGap(18, 18, 18)
                .addComponent(btn_stock)
                .addGap(18, 18, 18)
                .addComponent(btn_reports)
                .addGap(13, 13, 13)
                .addComponent(btn_profile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_logout)
                .addGap(502, 502, 502)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(u_name, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(u_type, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_logout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_reports, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_employee, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_profile, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 130));

        jPanel2.setBackground(new java.awt.Color(0, 204, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_grn.setBackground(new java.awt.Color(0, 204, 0));
        btn_grn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_grn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/grocery/images/9dff72a7f4e082be0150145258a82d16.png"))); // NOI18N
        btn_grn.setText("GRN");
        btn_grn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_grnActionPerformed(evt);
            }
        });
        jPanel2.add(btn_grn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 234, 71));

        btn_pos.setBackground(new java.awt.Color(0, 204, 0));
        btn_pos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_pos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/grocery/images/dashboard-3751501-3129908.png"))); // NOI18N
        btn_pos.setText("Dashboard");
        btn_pos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_posActionPerformed(evt);
            }
        });
        jPanel2.add(btn_pos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 234, 71));

        btn_brand.setBackground(new java.awt.Color(0, 204, 0));
        btn_brand.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_brand.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/grocery/images/5651266.png"))); // NOI18N
        btn_brand.setText("Brand");
        btn_brand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_brandActionPerformed(evt);
            }
        });
        jPanel2.add(btn_brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 234, 71));

        btn_pos1.setBackground(new java.awt.Color(0, 204, 0));
        btn_pos1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_pos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/grocery/images/401182.png"))); // NOI18N
        btn_pos1.setText("POS");
        btn_pos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pos1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_pos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 234, 71));

        btn_category.setBackground(new java.awt.Color(0, 204, 0));
        btn_category.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_category.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/grocery/images/icon-category.png"))); // NOI18N
        btn_category.setText("Category");
        btn_category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_categoryActionPerformed(evt);
            }
        });
        jPanel2.add(btn_category, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 234, 71));

        btn_po.setBackground(new java.awt.Color(0, 204, 0));
        btn_po.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_po.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/grocery/images/00_Magaya_Icons_White-BKG_PO_Managment.png"))); // NOI18N
        btn_po.setText("PO");
        btn_po.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_poActionPerformed(evt);
            }
        });
        jPanel2.add(btn_po, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 230, 71));

        btn_supplier.setBackground(new java.awt.Color(0, 204, 0));
        btn_supplier.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_supplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/grocery/images/supplier2.png"))); // NOI18N
        btn_supplier.setText("Supplier");
        btn_supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supplierActionPerformed(evt);
            }
        });
        jPanel2.add(btn_supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 234, 71));

        btn_po1.setBackground(new java.awt.Color(0, 204, 0));
        btn_po1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_po1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/grocery/images/00_Magaya_Icons_White-BKG_PO_Managment.png"))); // NOI18N
        btn_po1.setText("BIN");
        btn_po1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_po1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_po1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 230, 71));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 270, 780));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1020, 1920, 60));

        jDesktopPane1.setBackground(new java.awt.Color(0, 153, 51));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(1100, 450));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 1100, 780));

        setSize(new java.awt.Dimension(1316, 822));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void btn_posActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_posActionPerformed
        jDesktopPane1.removeAll();
        Dashboard p = new Dashboard();
        jDesktopPane1.add(p).setVisible(true);
    }//GEN-LAST:event_btn_posActionPerformed

    private void btn_categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_categoryActionPerformed
        jDesktopPane1.removeAll();
        Category c = new Category();
        jDesktopPane1.add(c).setVisible(true);
    }//GEN-LAST:event_btn_categoryActionPerformed

    private void btn_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stockActionPerformed
        jDesktopPane1.removeAll();
        Stock s = new Stock();
        jDesktopPane1.add(s).setVisible(true);
    }//GEN-LAST:event_btn_stockActionPerformed

    private void btn_grnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_grnActionPerformed
        jDesktopPane1.removeAll();
        GRN g = new GRN();
        jDesktopPane1.add(g).setVisible(true);
    }//GEN-LAST:event_btn_grnActionPerformed

    private void btn_brandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_brandActionPerformed
        jDesktopPane1.removeAll();
        Brand b = new Brand();
        jDesktopPane1.add(b).setVisible(true);
    }//GEN-LAST:event_btn_brandActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        Logger log = Logger.getLogger(Home.class.getName());
        log.info(SystemConfigData.getEmpid() + " Logout Successfully");
        Login l = new Login();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_poActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_poActionPerformed
        jDesktopPane1.removeAll();
        PO po = new PO();
        jDesktopPane1.add(po).setVisible(true);
    }//GEN-LAST:event_btn_poActionPerformed

    private void btn_pos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pos1ActionPerformed
        jDesktopPane1.removeAll();
        POS sup = new POS();
        jDesktopPane1.add(sup).setVisible(true);
    }//GEN-LAST:event_btn_pos1ActionPerformed

    private void btn_profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_profileActionPerformed
            new Userprofile().setVisible(true);
    }//GEN-LAST:event_btn_profileActionPerformed

    private void btn_reportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reportsActionPerformed
        // TODO add your handling code here:

        jDesktopPane1.removeAll();
        Report rep = new Report();
        jDesktopPane1.add(rep).setVisible(true);
    }//GEN-LAST:event_btn_reportsActionPerformed

    private void btn_supplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supplierActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        Supplier sup = new Supplier();
        jDesktopPane1.add(sup).setVisible(true);
    }//GEN-LAST:event_btn_supplierActionPerformed

    private void btn_employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_employeeActionPerformed
        // TODO add your handling code here:

        jDesktopPane1.removeAll();
        Employee emp = new Employee();
        jDesktopPane1.add(emp).setVisible(true);
        
    }//GEN-LAST:event_btn_employeeActionPerformed

    private void btn_po1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_po1ActionPerformed
        // TODO add your handling code here:
        new Inactiveted_Types().setVisible(true);
    }//GEN-LAST:event_btn_po1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_brand;
    private javax.swing.JButton btn_category;
    private javax.swing.JButton btn_employee;
    private javax.swing.JButton btn_grn;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_po;
    private javax.swing.JButton btn_po1;
    private javax.swing.JButton btn_pos;
    private javax.swing.JButton btn_pos1;
    private javax.swing.JButton btn_profile;
    private javax.swing.JButton btn_reports;
    private javax.swing.JButton btn_stock;
    private javax.swing.JButton btn_supplier;
    private javax.swing.JPanel jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel u_name;
    private javax.swing.JLabel u_type;
    // End of variables declaration//GEN-END:variables

    private void showbutton() {
        String usertype = SystemConfigData.getUsertype();
        if (usertype.trim().equals("Admin")) {
            btn_profile.setEnabled(true);
        } else {
            btn_profile.setEnabled(false);
        }
    }
}
